/*
 * Hibernate, Relational Persistence for Idiomatic Java
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later
 * See the lgpl.txt file in the root directory or http://www.gnu.org/licenses/lgpl-2.1.html
 */

apply plugin: 'maven-publish'

// Disable Gradle module metadata publishing
tasks.withType(GenerateModuleMetadata) {
    enabled = false
}

publishing {
    publications {
        publishedArtifacts {
            pom {
                name = 'Hibernate ORM - ' + project.name
                description = project.description ?: "Hibernate ORM ${project.name} module"
                url = 'https://hibernate.org/orm'

                organization {
                    name = 'Hibernate.org'
                    url = 'https://hibernate.org'
                }

                licenses {
                    license {
                        name = 'GNU Lesser General Public License v2.1 or later'
                        url = 'https://www.opensource.org/licenses/LGPL-2.1'
                        comments = 'See discussion at https://hibernate.org/community/license/ for more details.'
                        distribution = 'repo'
                    }
                }

                scm {
                    url = 'https://github.com/atlassian/hibernate-orm'
                    connection = 'scm:git:https://github.com/atlassian/hibernate-orm.git'
                    developerConnection = 'scm:git:git@github.com:atlassian/hibernate-orm.git'
                }

                issueManagement {
                    system = 'jira'
                    url = 'https://hibernate.atlassian.net/browse/HHH'
                }

                developers {
                    developer {
                        id = 'hibernate-team'
                        name = 'The Hibernate Development Team'
                        organization = 'Hibernate.org'
                        organizationUrl = 'https://hibernate.org'
                    }
                }
            }
        }
    }
}
